### ISSUE TITLE
Error JS on console, jquery.cookie seems to be not loaded properly

### ISSUE THREAD

**Issue by yosefkurniawan** [antonkril/magento-rjs-config#4]
Hi @antonkril 
I really appreciate this idea. Running Magento with bundle js should make the performance better. 

Anyway, I am trying to implement this r.js bundling on Luma. The bundles files are generated successfully. They are loaded on the related page successfully as well. Unfortunately, it is not really working.
There is an error in the console. Here is the error:
<img width="1418" alt="error on console" src="https://user-images.githubusercontent.com/6382194/40575342-6c07e9d6-610d-11e8-9379-51a642693016.png">
<img width="620" alt="error location" src="https://user-images.githubusercontent.com/6382194/40575346-6f7e8cbe-610d-11e8-9a92-91805b765b87.png">

I am guessing seems the jquery.cookie is not loaded properly.
Is it related to your concern about the cookies issue on this part? https://github.com/antonkril/magento-rjs-config/#fixing-missconfiguration-of-jquerycookie
I did try this step, I was creating a new requirejs-config.js under Magento_Theme module, and put the jquery/jquery.cookie as deps there. But the error persist, it bring another error on console instead.
<img width="593" alt="another error" src="https://user-images.githubusercontent.com/6382194/40575383-55073d26-610e-11e8-9b11-7691f3fc51b8.png">
Both error actually are similar. it says that cookieStorage is not defined.

Do you have any idea about what is going on here?
Thank you very much in advance! Really appreciate your help.

**Comment by yosefkurniawan** [comment]
Hi, I am able to fix this issue by adding "jquery/jquery.cookie" in jquery/storageapi.min.js as a dependency. Need to add there because the Shim that write down in build.js for this file doesn't work since this file supports AMD. As far as I know, shim won't work for a file that already support AMD.

I'm leaving a comment here just in case if someone else facing the same issue.
Cheers 🍻

**Comment by anemitoff** [comment]
Thanks @yosefkurniawan, your fix does work.

But, is there any other way to fix this?!?  I want to edit "build.js" which is a file that I "own" rather than "jquery.storageapi.min.js"?

**Comment by Vinai** [comment]
Interesting, I wonder what is different. For me the problem isn't ocuring.

**Comment by rossmc** [comment]
The solution to this issue is described at the end of the readme under **Fixing missconfiguration of jquery.cookie**.

Thanks @antonkril , this is very useful.  Any idea when Magento will have something similar to release, I can't see anything on their [gitgub](https://github.com/magento).  I presume they will use [requirejs optimiser](https://requirejs.org/docs/optimization.html) too.

**Comment by antonkril** [comment]
@rossmc @Vinai see https://devdocs.magento.com/guides/v2.3/performance-best-practices/advanced-js-bundling.html

**Comment by lima195** [comment]
I had this same issue upgrading a magento ee 2.4.3 to 2.4.6.
The fix was remove the /lib directory and get a new lib from version 2.4.6.

**Comment by jsutariya** [comment]
Hello @lima195 , I am facing the same issue after upgrading. I replaced lib but the issue is still there. Do you have any other suggestions?

**Comment by lima195** [comment]
> Hello @lima195 , I am facing the same issue after upgrading. I replaced lib but the issue is still there. Do you have any other suggestions?

Check your third party modules, there should be some module overriting some lib file.

I would recommend get a new and fresh installation of magento 2.4.6 and copy the core files to your store, because sometimes you will need update that lib, dev, and other directories and files...

Also, if you are using docker, could you check if the files from your container and computer are the same... There is some good docker images that only sync app/code files for instance to improve performance...
